const constants = {
    CANVAS_MAXIMUM_WIDTH : 32767,
    CANVAS_MAXIMUM_HEIGHT: 32767,
    MAXIMUM_NODES : 120,
    MINIMUM_NODES:  20,
    NODE_RADIUS: 25,
    NODE_DRAW_FONT: '15px Arial',
    NODE_PATH_COLOR: 'yellow',
    NODE_SELECTED_COLOR: '#00FFFF',
    NODE_CURRENT_COLOR :'green',
    MINIMUM_SPEED:20,
    MAXIMUM_SPEED:1000
};
export default constants;